# Generated by Django 6.0.4 on 2026-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_movies_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='is_serie',
            field=models.BooleanField(default=False),
        ),
    ]
